### ISSUE TITLE
DCV Viewer does not connect

### ISSUE THREAD

**Issue by schw4rzlicht** [aws-samples/cloud-gaming-on-ec2-instances#18] opened 2023-12-25 18:16 UTC
Hey there,

I was following along the readmes and got everything working - but DCV. I am trying to connect with the macOS client but I don't see anything besides the loading screen.

![Bildschirmfoto 2023-12-25 um 19 15 48](https://github.com/aws-samples/cloud-gaming-on-ec2-instances/assets/19175262/8a575662-77da-4959-9adc-bbfc91910ff7)

Sometimes I hear a windows chime that must come through DCV but nothing else. Logs have only info messages but nothing else.

**Comment by adrianloffredo** [comment] 2024-01-04 15:23
Same issue for me. Logs don't seem to show much. There does seem to be a connection being made.

I tried connecting without QUIC using web sockets instead and through the browser but got the same result.

RDP and Parsec work (with correct ports being opened)

I did not have the time to go over the registry entries for DCV though. Maybe something is not happening during the installation.

**Comment by adrianloffredo** [comment] 2024-01-08 10:23
So I think there is an issue with the registry entries in the cds/lib/base.ts file based on the last commit.

I tested on the g5 and g4ad and the issue was the same.

On the g4ad instance registry entries, I commented out target-fps, enable-q, frame-queue-weights and connectivity-console-session. I also added back automatic-console-session. 

I basically rolled back the last commit for that block of code but kept the quic entry.

With that, I was able to connect with quic.

I assume all those regedits are for performance tweaks and improvements but not sure which one is causing the issue.

![image](https://github.com/aws-samples/cloud-gaming-on-ec2-instances/assets/21286008/daf97e47-a1c0-4e6f-a7fb-7d8f1c74bbdc)

**Comment by markusz** [comment] 2024-01-09 08:35
Hi @schw4rzlicht,

thanks for raising this. @Seblat5ch, seems that regression was introduced in by your [commits](https://github.com/aws-samples/cloud-gaming-on-ec2-instances/pull/9/commits) - can you please have a look at it please?

**Comment by Seblat5ch** [comment] 2024-02-09 15:42
Hi, I will take a look at this. I think it is because of the latest version of NiceDCV. Let me test this and ether hard code the NiceDCV version or something else.

**Comment by philippevezina** [comment] 2024-02-10 04:50
This did the same thing on my end. What I had to do was uninstall NiceDCV Server and NiceDCV Virtual Display Driver which were preinstalled on my remote machine. I reinstalled them and this fixed the issue.

**Comment by Seblat5ch** [comment] 2024-02-20 10:55
resolved with latest commit #[69482d0](https://github.com/aws-samples/cloud-gaming-on-ec2-instances/commit/69482d0af8535dd9d4c458fd61d5ca3a469559e5)

**Closed by Seblat5ch** 2024-02-20 10:55 UTC
